### ISSUE TITLE
Value of count error applying iam binding.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [terraform-google-modules/terraform-google-iam#25] opened 2019-06-10 18:19 UTC
```
provider "google" {
  region = "${var.region}"
  credentials = "${file("./auth.json")}"
  project     = "${var.seed_project_id}"
}

provider "google-beta" {
  region = "${var.region}"
  credentials = "${file("./auth.json")}"
  project     = "${var.seed_project_id}"
}


provider "google-beta-janus" {
  region = "${var.region}"
  credentials = "${file("./auth.json")}"
  project     = "${var.seed_project_id}"
}

module "folder_iam_binding" {
  source = "terraform-google-modules/iam/google"
  mode   = "authoritative"

  folders = ["${google_folder.enironment.id}"]

  bindings = {

    "roles/editor" = [
      "${var.sysadmins}"
    ]

    "roles/editor" = [
      "${var.securityadmins}"
    ]

    "roles/viewer" = [
      "${var.developers}"
    ]

    "roles/logging.viewer" = [
      "${var.developers}"
    ]

    "roles/storage.objectViewer" = [
      "${var.developers}"
    ]

  }
}
```
Error: Error refreshing state: 1 error(s) occurred:

* module.janus_environment_folder.module.folder_iam_binding.data.google_project.project_from_provider: data.google_project.project_from_provider: value of 'count' cannot be computed

The provider does specify the project.  The same template worked last week and I don't have the module version pinned - so I am a little confused on what changed.

**Comment by aaron-lane** [comment] 2019-06-10 20:11
@mikhail-khodorovskiy can you please confirm which version of the module worked and which version is causing this error?

**Comment by mikhail-khodorovskiy** [comment] 2019-06-10 20:33
I tried all versions 1.1.1, 1.1.0, and 1.0.0.

**Comment by aaron-lane** [comment] 2019-06-10 21:15
@mikhail-khodorovskiy does you mean to say that all versions worked last week and none of the versions work this week?

**Comment by gokeefe** [comment] 2019-06-10 21:57
I'm seeing the same issue. Tried downgrading both the terraform-google-iam module and the google and google-beta providers and get the same `value of 'count' cannot be computed` errors.

**Comment by aaron-lane** [comment] 2019-06-11 20:23
@mikhail-khodorovskiy is the problem resolved if you provide a hard-coded value for the folder ID?

**Comment by mikhail-khodorovskiy** [comment] 2019-06-12 17:50
I am not pinning the terraform provider version which may be what had fixed it but the IAM binding module version 1.1.1 works for me today.

**Comment by morgante** [comment] 2019-06-12 17:56
Excellent, thank you for the update.

**Comment by mikhail-khodorovskiy** [comment] 2019-06-13 22:33
It turns out it's still a problem during plan/apply when the folder referenced has not been crated yet, but works if the folder id is hard-coded.  I am not sure what's going on here.

**Comment by aaron-lane** [comment] 2019-06-18 17:07
Related to #4

**Comment by paulpalamarchuk** [comment] 2019-08-01 09:27
@mikhail-khodorovskiy workaround (according to the current provider version `2.11`) is to define environment variable `GOOGLE_PROJECT`.

**Comment by aaron-lane** [comment] 2019-09-06 16:25
Duplicate of #4.

**Closed by aaron-lane** 2019-09-06 16:25 UTC
Labels: bug
